export const labOffers = [
  "Advanced Biomarker Test",
  "Advanced Blood Count Panel",
  " Advanced Cholesterol Panel",
  " Advanced Fatty Acid Test",
  " Advanced Hormone Panel",
  " Advanced Inflammation Panel",
  " Advanced Metabolic Panel",
  " Advanced Rheumatology Panel",
  " Advanced Thyroid Panel",
  " Advanced Vitamin Panel",
  " Basic Blood Count Panel",
  " Basic Cholesterol Panel",
  " Basic Infection Panel",
  " Basic Iron Panel",
  " Basic Liver Panel",
  " Basic Metabolic Panel",
  " Basic Thyroid Panel",
  " Basic Urine Panel",
  " Basic Vitamin Panel",
  " Blood Panel",
  " Coagulation Panel",
  " Genetic Panel",
  " Hypercoagulable Panel",
  " Inflammation Panel",
  " Pregnancy Testing Panel",
  " Stool Testing Panel",
];

export const howWeCanHelp = [
  "Advanced Chronic Disease Testing",
  "Cancer Screening And Prevention",
  "Cardiovascular Health",
  "Healthful Use Of Substances",
  "Hormone Imbalance",
  "Lifestyle Modification",
  "Mental Health",
  "Metabolic Health",
  "Optimizing Nutritional Status",
  "Preventative Health",
  "Sleep Disturbance",
  "Stress Management",
  "Vitamin Deficiency",
  "Weight Management",
];
